Content:
    tutorial03_verification:
        root_dir: !include tutorials/tutorial03_verification/doc/config.yml Content tutorial03_verification root_dir
        content:
            - getting_started/examples_and_tutorials/tutorial03_verification/**

Renderer: !include tutorials/tutorial03_verification/doc/config.yml Renderer
Extensions: !include tutorials/tutorial03_verification/doc/config.yml Extensions
