Content:
    thm:
        root_dir: ${ROOT_DIR}/doc/content
    thm_test:
        root_dir: ${ROOT_DIR}/test/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content
        content:
            - /**
            - ~syntax/Modules/index.md
            - ~syntax/Modules/FluidProperties/index.md
    misc:
        root_dir: ${MOOSE_DIR}/modules/misc/doc/content
    heat_conduction:
        root_dir: ${MOOSE_DIR}/modules/heat_conduction/doc/content
        content:
            - /**
            - ~syntax/ThermalContact/index.md
            - ~source/materials/GapConductanceConstant.md
            - ~source/actions/ThermalContactAction.md
            - ~source/actions/ThermalContactBCsAction.md
            - ~source/actions/ThermalContactMaterialsAction.md
            - ~source/actions/AddSlaveFluxVectorAction.md
            - ~source/actions/ThermalContactAuxBCsAction.md
            - ~source/actions/ThermalContactAuxVarsAction.md
            - ~source/actions/ThermalContactDiracKernelsAction.md
    rdg:
        root_dir: ${MOOSE_DIR}/modules/rdg/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: 'THM'
        repo: https://hpcgitlab.hpc.inl.gov/idaholab/thm
        home: https://hpcsc.inl.gov/ssl/THM/site/
        menu:
            Systems: syntax/index.md
            Build Status: https://moosebuild.inl.gov/repo/idaholab/thm/

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        allow-test-objects: True
        hide:
            framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/hidden.yml
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/hidden.yml
            misc: !include ${MOOSE_DIR}/modules/misc/doc/hidden.yml
            thm: !include ${ROOT_DIR}/doc/hidden.yml
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
            heat_conduction:
                - /ThermalContact
            thm:
                - /Modules
            fluid_properties_test_app:
                - /Materials/MultiComponentFluidPropertiesMaterialPT
                - /AuxKernels/TwoPhaseAverageDensityAux
        alias:
            /FluidProperties: /Modules/FluidProperties
            /FluidProperties/AddFluidPropertiesAction: /Modules/FluidProperties/AddFluidPropertiesAction
            /FluidProperties/BrineFluidProperties: /Modules/FluidProperties/BrineFluidProperties
            /FluidProperties/CO2FluidProperties: /Modules/FluidProperties/CO2FluidProperties
            /FluidProperties/FlibeFluidProperties: /Modules/FluidProperties/FlibeFluidProperties
            /FluidProperties/FlinakFluidProperties: /Modules/FluidProperties/FlinakFluidProperties
            /FluidProperties/GeneralVaporMixtureFluidProperties: /Modules/FluidProperties/GeneralVaporMixtureFluidProperties
            /FluidProperties/HeliumFluidProperties: /Modules/FluidProperties/HeliumFluidProperties
            /FluidProperties/IdealGasFluidProperties: /Modules/FluidProperties/IdealGasFluidProperties
            /FluidProperties/IdealGasFluidPropertiesPT: /Modules/FluidProperties/IdealGasFluidPropertiesPT
            /FluidProperties/MethaneFluidProperties: /Modules/FluidProperties/MethaneFluidProperties
            /FluidProperties/NaClFluidProperties: /Modules/FluidProperties/NaClFluidProperties
            /FluidProperties/NitrogenFluidProperties: /Modules/FluidProperties/NitrogenFluidProperties
            /FluidProperties/HydrogenFluidProperties: /Modules/FluidProperties/HydrogenFluidProperties
            /FluidProperties/SimpleFluidProperties: /Modules/FluidProperties/SimpleFluidProperties
            /FluidProperties/SodiumProperties: /Modules/FluidProperties/SodiumProperties
            /FluidProperties/StiffenedGasFluidProperties: /Modules/FluidProperties/StiffenedGasFluidProperties
            /FluidProperties/TabulatedFluidProperties: /Modules/FluidProperties/TabulatedFluidProperties
            /FluidProperties/TwoPhaseFluidPropertiesIndependent: /Modules/FluidProperties/TwoPhaseFluidPropertiesIndependent
            /FluidProperties/Water97FluidProperties: /Modules/FluidProperties/Water97FluidProperties
            /FluidProperties/IdealRealGasMixtureFluidProperties: /Modules/FluidProperties/IdealRealGasMixtureFluidProperties
            /FluidProperties/LinearTest7EqnFluidProperties: /Modules/FluidProperties/LinearTest7EqnFluidProperties
        includes:
            - ${MOOSE_DIR}/framework/include
            - ${MOOSE_DIR}/modules/fluid_properties/include
            - ${MOOSE_DIR}/modules/heat_conduction/include
            - ${MOOSE_DIR}/modules/misc/include
            - include
            - test/include

    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
            thm:
                Components: systems/Components/index.md

    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml

    MooseDocs.extensions.bibtex:
        duplicate_warning: False
