Content:
    THM:
        root_dir: ${ROOT_DIR}/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: THM

Extensions:
    MooseDocs.extensions.navigation:
        menu:
            Developers:
                Build Status: https://moosebuild.inl.gov/repo/idaholab/thm/

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        hide:
            framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/hidden.yml
            thm: !include ${ROOT_DIR}/doc/hidden.yml
        includes:
            - include
            - ${MOOSE_DIR}/framework/include
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml

    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml

    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
