Content:
    framework:
        root_dir: framework/doc/content
    chemical_reactions:
        root_dir: modules/chemical_reactions/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Translator:
    # remove with #24406
    ignore_content_key: False

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Chemical Reactions Module
        repo: https://github.com/idaholab/moose
        home: /modules/chemical_reactions/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/chemical_reactions
        remove:
            framework: !include framework/doc/remove.yml
        unregister:
            framework: !include framework/doc/unregister.yml
        includes:
            - framework/include
            - modules/chemical_reactions/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa: disable
    MooseDocs.extensions.autolink:
        # remove with #24406
        explicit: True
