moose_python:
  - python 3.10
  - python 3.9
  - python 3.8

moose_libclang:
  - libclang 14.0.6 default_h7634d5b_1                      # [linux]
  - libclang 14.0.6 default_hdb78580_1                      # [not arm64 and osx]
  - libclang 14.0.6 default_h5dc8d65_1                      # [arm64]

moose_libclang13:
  - libclang13 14.0.6 default_h9986a30_1                    # [linux]
  - libclang13 14.0.6 default_h953c2e9_1                    # [not arm64 and osx]
  - libclang13 14.0.6 default_hc7183e1_1                    # [arm64]

# Pesky packages that break internal CI
# Note: Modifying/Updating this will require changes to conda/mpich!
setuptools:
  - <60.0
pin_run_as_build:
  setuptools: x.x
