{% set build = 0 %}
{% set version = "2021.07.23" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: {{ build }}

requirements:
  build:
    - python {{ moose_python }}

  run:
    - gcc_linux-64       {{ moose_gcc }}            # [linux]
    - gxx_linux-64       {{ moose_gxx }}            # [linux]
    - gfortran_linux-64  {{ moose_fortran }}        # [linux]
    - gcc_impl_linux-64  {{ moose_gccimpl }}        # [linux]
    - clang              {{ moose_clang }}          # [osx]
    - clang_osx-64       {{ moose_clangosx }}       # [osx]
    - clangxx            {{ moose_clangxx }}        # [osx]
    - clangxx_osx-64     {{ moose_clangxxosx }}     # [osx]
    - compiler-rt        {{ moose_compilerrt }}     # [osx]
    - compiler-rt_osx-64 {{ moose_compilerrtosx }}  # [osx]
    - libllvm11          {{ moose_libllvm }}        # [osx]
    - clang-tools                                   # [osx]
    - llvm-openmp        {{ moose_llvmopenmp }}     # [osx]
    - gfortran_osx-64    {{ moose_osxfortran }}     # [osx]
    - libclang           {{ moose_libclang }}       # [osx]
    - libcxx             {{ moose_libcxx }}         # [osx]
    - libblas            {{ moose_libblas }}        # [osx]
    - libcblas           {{ moose_libcblas }}       # [osx]
    - liblapack          {{ moose_liblapack }}      # [osx]
    - libopenblas        {{ moose_libopenblas }}    # [osx]
    - vtk                {{ moose_vtk }}
    - numpy              {{ moose_numpy }}
    - pyqt               {{ moose_pyqt }}
    - matplotlib         {{ moose_matplotlib }}
    - pandas             {{ moose_pandas }}
    - livereload         {{ moose_livereload }}
    - yaml               {{ moose_yaml }}
    - pyyaml             {{ moose_pyyaml }}
    - beautifulsoup4     {{ moose_beautifulsoup4 }}
    - pybtex             {{ moose_pybtex }}
    - mock               {{ moose_mock }}
    - lxml               {{ moose_lxml }}
    - scikit-image       {{ moose_scikit_image }}
    - pylatexenc         {{ moose_pylatexenc }}
    - jinja2             {{ moose_jinja2 }}
    - mako               {{ moose_mako }}
    - python

test:
  imports:
    - numpy
    - PyQt5
    - matplotlib
    - pandas
    - livereload
    - yaml
    - bs4
    - pybtex
    - mock
    - lxml
    - skimage
    - vtk
    - pylatexenc
    - jinja2

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-tools) acts as a top-level module designed to provide all dependencies required in order to run Peacock and MOOSE Documentation.'

extra:
  recipe-maintainers:
    - milljm
