CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

libllvm:
  - 11.0.1 h223d4b2_0

libclang:
  - 11.0.1 default_hf8bb9ca_1

compilerrt:
  - 11.0.1 h654b07c_0

compilerrtosx:
  - 11.0.1 h8c5fa43_0

clangxx:
  - 11.0.1 default_hf8bb9ca_1

clangosx:
  - 11.0.1 hb91bd55_2

clangxxosx:
  - 11.0.1 h7e1b574_2

clang:
  - 11.0.1 h694c41f_1

llvmopenmp:
  - 11.0.1 h7c73e74_0

osxfortran:
  - 9.3.0 h18f7dce_13

libcxx:
  - 11.0.1 habf9029_0

gcc:
  - 9.3.0 h7247604_29

gxx:
  - 9.3.0 h0d07fa4_29

fortran:
  - 9.3.0 ha1c937c_29

gccimpl:
  - 9.3.0 h28f5a38_17

moose_compilers:
  - 2020.12.17
