#### Compilers
base_mpich:
  - mpich 4.0.3

base_mpicc:
  - mpich-mpicc 4.0.3

base_mpicxx:
  - mpich-mpicxx 4.0.3

base_mpifort:
  - mpich-mpifort 4.0.3

moose_libgfortran:
  - libgfortran-ng 12.2.0 h69a702a_19                       # [linux]
  - libgfortran 5.0.0 9_5_0_h97931a8_26                     # [not arm64 and osx]
  - libgfortran 5.0.0 11_3_0_hd922786_26                    # [arm64]

moose_libgfortran5:
  - libgfortran5 12.2.0 h337968e_19                         # [linux]
  - libgfortran5 11.3.0 h082f757_26                         # [not arm64 and osx]
  - libgfortran5 11.3.0 hdaf2cc0_26                         # [arm64]

moose_ld64:                                                 # [osx]
  - ld64 609                                                # [not arm64 and osx]
  - ld64_osx-arm64 609                                      # [arm64]

moose_hdf5:
  - hdf5 1.12.1 mpi_mpich_h611ac81_4                        # [not arm64 and osx]
  - hdf5 1.12.1 mpi_mpich_h5d83325_4                        # [linux]
  - hdf5 1.12.1 mpi_mpich_hc830fdb_4                        # [arm64]

mpi:
  - moose-mpich

#### Support Libraries
moose_libxt:                                                # [linux]
  - libxt-devel-cos7-x86_64 1.1.5                           # [linux]

moose_libsm:                                                # [linux]
  - libsm-devel-cos7-x86_64 1.2.2                           # [linux]

moose_libx11:                                               # [linux]
  - libx11-devel-cos7-x86_64 1.6.7                          # [linux]

moose_libice:                                               # [linux]
  - libice-devel-cos7-x86_64 1.0.9                          # [linux]

moose_libxext:                                              # [linux]
  - libxext-devel-cos7-x86_64 1.3.3                         # [linux]

moose_mesa_libgl:                                           # [linux]
  - mesa-libgl-devel-cos7-x86_64 18.3.4                     # [linux]

moose_xorg_x11:                                             # [linux]
  - xorg-x11-proto-devel-cos7-x86_64 2018.4                 # [linux]

moose_libglu:                                               # [linux]
  - libglu 9.0.0                                            # [linux]

moose_mesalib:                                              # [linux]
  - mesalib 18.3.1                                          # [linux]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
