#### The idea here is that anything below something else requires
#### anything above that to be updated.

moose_libmesh:
  - 2021.06.30 build_1

moose_petsc:
  - 3.15.1 build_1

moose_libmesh_vtk:
  - 6.3.0 build_6

moose_mpich:
  - 3.3.2 build_6

# required for libmesh/build.sh
SHORT_VTK_NAME:
  - 6.3

vtk_version:
  - 6.3.0

#### Changes to the following require extensive testing
libllvm:
  - 11.0.0 hf85e3d2_0

libclang:
  - 11.0.0 default_h9e6edd0_2

compilerrt:
  - 11.0.0 h01488ec_2

compilerrtosx:
  - 11.0.0 hd3c4e95_2

clangxx:
  - 11.0.0 default_h9e6edd0_2

clangosx:
  - 11.0.0 hb91bd55_5

clangxxosx:
  - 11.0.0 h7e1b574_5

clang:
  - 11.0.0 h694c41f_2

llvmopenmp:
  - 11.0.0 h73239a0_1

osxfortran:
  - 7.3.0 h22b1bf0_7

libcxx:
  - 11.0.0 h4c3b8ed_1

gcc:
  - 9.3.0 h7247604_29

gxx:
  - 9.3.0 h0d07fa4_29

fortran:
  - 9.3.0 ha1c937c_29

gccimpl:
  - 9.3.0 h28f5a38_17

libblas:
  - 3.9.0 8_openblas           # [osx]

libcblas:
  - 3.9.0 8_openblas           # [osx]

liblapack:
  - 3.9.0 8_openblas           # [osx]

libopenblas:
  - 0.3.12 openmp_h63d9170_1   # [osx]

libglu:
  - 9.0.0 hf484d3e_1000        # [linux]

mesalib:
  - 18.3.1 h590aaf7_0          # [linux]

netcdf:
  - 4.6.2

libpng:
  - 1.6.37 h7cec526_2          # [osx]
  - 1.6.37 hed695b0_2          # [linux]

# You simply _never_ change the following
mpi:
  - moose-mpich

pin_run_as_build:
  moose_mpich: x.x.x
  libblas: x.x.x
  libcblas: x.x.x
  liblapack: x.x.x
  moose_petsc: x.x.x
  moose_libmesh_vtk: x.x.x

CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]
