{% set build = 1 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0" %}

package:
  name: moose-mpich
  version: {{ version }}

source:
  - path: .

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('moose-mpich', max_pin='x.x') }}

requirements:
  build:
    - {{ base_mpich }}
    - {{ moose_cc }}
    - {{ moose_cxx }}
    - {{ moose_fortran }}
    - {{ moose_impl }}          # [linux]
    - {{ moose_impl_xx }}       # [linux]
    - {{ moose_libgcc }}        # [linux]
    - {{ moose_libstd }}        # [linux]
    - {{ moose_sysroot }}       # [linux]
    - {{ moose_libcxx }}        # [osx]
    - {{ moose_libclang }}      # [osx]
    - {{ moose_openmp }}        # [osx]
    - {{ moose_llvm_tools }}    # [osx]
    - {{ moose_ld64 }}          # [osx]
    - autoconf                  # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - make                      # [unix]
    - gnuconfig                 # [arm64]
  host: []
  run:
    - {{ base_mpich }}
    - {{ moose_cc }}
    - {{ moose_cxx }}
    - {{ moose_fortran }}
    - {{ moose_impl }}          # [linux]
    - {{ moose_impl_xx }}       # [linux]
    - {{ moose_libgcc }}        # [linux]
    - {{ moose_libstd }}        # [linux]
    - {{ moose_sysroot }}       # [linux]
    - {{ moose_libcxx }}        # [osx]
    - {{ moose_libclang }}      # [osx]
    - {{ moose_openmp }}        # [osx]
    - {{ moose_llvm_tools }}    # [osx]
    - {{ moose_ld64 }}          # [osx]
    - autoconf                  # [osx]
    - automake                  # [osx]
    - libtool                   # [osx]
    - make                      # [osx]
    - {{ pin_compatible('setuptools', lower_bound='58', upper_bound='60') }}
    - mpi 1.0 mpich
test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate_moose-mpich.sh

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'Top Level packages designed to control environment variables for conda-forge mpich'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
