{% set version = "2024.08.30" %}

package:
  name: moose-pyhit
  version: {{ version }}

source:
  - path: ../pyhit
  - path: ../../python/moosetree
    folder: pyhit/moosetree
  - path: ../../python/mooseutils/message.py
    folder: pyhit/mooseutils/message.py
  - path: ../../python/mooseutils/mooseutils.py
    folder: pyhit/mooseutils/mooseutils.py
  - path: ../../framework/contrib/hit
    folder: src
  - path: ../../python/pyhit/pyhit.py
    folder: pyhit
  - patches:
      - pyhit.patch

build:
  number: 0
  string: build_0
  skip: true           # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ moose_python }}
    - {{ moose_wasp }}
    - make
    - cython
    - setuptools

  host:
    - {{ moose_python }}

  run:
    - {{ moose_wasp }}
    - python

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
