{% set version = "2.10" %}
{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set sha256 = "83e3bfdd28b8bcf53222c3798d4d395d52dadbbae59e8730c4a6d31a9c3732d8" %}

package:
  name: moose-gperftools
  version: {{ version }}

source:
  fn: gperftools-{{ version }}.tar.gz
  url: https://github.com/gperftools/gperftools/releases/download/gperftools-{{ version }}/gperftools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libunwind                          # [linux]
    - sysroot_linux-64 2.17              # [linux64]
    - gnuconfig                          # [unix]
    - go
  run:
    - perl

test:
  commands:
    - pprof --help

about:
  home: https://github.com/gperftools/gperftools
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'The fastest malloc we have seen; works particularly well with threads and STL'
  description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
  doc_url: https://github.com/gperftools/gperftools/wiki
  dev_url: https://github.com/gperftools/gperftools

extra:
  recipe-maintainers:
    - milljm
