CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

mpi:
  - moose-mpich

moose_mpich:
  - 3.3.2 build_6

libblas:
  - 3.9.0 8_mkl

libcblas:
  - 3.9.0 8_mkl

liblapack:
  - 3.9.0 8_mkl

libopenblas:
  - 0.3.13 openmp_hb927a7c_0

pin_run_as_build:
  moose_mpich: x.x.x
  libblas: x.x.x
  libcblas: x.x.x
  liblapack: x.x.x
