Content:
    - framework/doc/content
    - modules/scalar_transport/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: scalar_transport
        repo: https://github.com/idaholab/moose
        home: /modules/scalar_transport
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/scalar_transport
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/scalar_transport/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            scalar_transport: !include ${ROOT_DIR}/modules/scalar_transport/doc/sqa_scalar_transport.yml
        reports: !include ${ROOT_DIR}/modules/scalar_transport/doc/sqa_reports.yml
    MooseDocs.extensions.template:
        active: true
