Content:
  framework:
    root_dir: framework/doc/content
  optimization:
    root_dir: modules/optimization/doc/content
  modules:
      root_dir: modules/doc/content
      content:
          - help/development/analyze_jacobian.md

Renderer:
  type: MooseDocs.base.MaterializeRenderer

Translator:
    # remove with #24406
    ignore_content_key: False

Extensions:
  MooseDocs.extensions.navigation:
    name: MOOSE Optimization Module
    repo: https://github.com/idaholab/moose
    home: /modules/optimization/index.md

  MooseDocs.extensions.appsyntax:
    executable: ${MOOSE_DIR}/modules/optimization
    remove:
      framework: !include framework/doc/remove.yml
    unregister:
      framework: !include framework/doc/unregister.yml
    includes:
        - framework/include
        - modules/optimization/include

  MooseDocs.extensions.common:
    shortcuts: !include framework/doc/globals.yml
  MooseDocs.extensions.acronym:
    acronyms: !include framework/doc/acronyms.yml
  MooseDocs.extensions.template:
        active: True
  MooseDocs.extensions.sqa:
      active: True
      reports: !include modules/optimization/doc/sqa_reports.yml
      categories:
          framework: !include framework/doc/sqa_framework.yml
          optimization: !include modules/optimization/doc/sqa_optimization.yml

  MooseDocs.extensions.algorithm:
      active: True
  MooseDocs.extensions.autolink:
      # remove with #24406
      explicit: True
