{% set version = "2024.06.11" %}

package:
  name: moose-pprof
  version: {{ version }}

source:
  path:
    ../pprof

build:
  number: 0
  string: build_0
  skip: true  # [win]
  missing_dso_whitelist:
    - System
    - resolve
    - CoreFoundation
    - CommonAuth
    - Security
    - c++abi
    - system_malloc
  runpath_whitelist:
    - System
    - resolve
  ignore_run_exports:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libcxx
    - gperftools
    - perl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - gperftools
    - libunwind                          # [linux]
    - sysroot_linux-64 2.17              # [linux64]
    - gnuconfig                          # [unix]
    - go

  run:
    - gperftools
    - graphviz
    - perl
    - setuptools <60

test:
  commands:
    - pprof --help

about:
  home: https://github.com/google/pprof
  license: Apache
  license_family: BSD
  license_file: LICENSE
  summary: 'pprof is a tool for visualization and analysis of profiling data.'
  description: |
    pprof reads a collection of profiling samples in profile.proto format and
    generates reports to visualize and help analyze the data. It can generate
    both text and graphical reports (through the use of the dot visualization
    package).
  doc_url: https://github.com/google/pprof
  dev_url: https://github.com/google/pprof

extra:
  recipe-maintainers:
    - milljm
