Content:
    framework:
        root_dir: framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**
            - media/**
    richards:
        root_dir: modules/richards/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Translator:
    # remove with #24406
    ignore_content_key: False

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Richards Module
        repo: https://github.com/idaholab/moose
        home: /modules/richards/index.md
    MooseDocs.extensions.appsyntax:
        active: False
    MooseDocs.extensions.autolink:
        # remove with #24406
        explicit: True
